/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/C40FOQFqCg6
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Sheet, SheetTrigger, SheetContent } from "@/components/ui/sheet"
import { Card, CardContent } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"

export function ComponentThree() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header
        className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <HospitalIcon className="h-6 w-6" />
          <span className="text-xl font-semibold">Acme Hospital</span>
        </Link>
        <nav className="hidden md:flex items-center gap-4">
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Services
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Doctors
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            About
          </Link>
          <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
            Contact
          </Link>
        </nav>
        <Button className="hidden bg-secondary border-2 border-secondary md:inline-flex">
          Contact Us
        </Button>
        <Sheet>
          <SheetTrigger asChild>
            <Button variant="outline" size="icon" className="md:hidden">
              <MenuIcon className="h-6 w-6" />
              <span className="sr-only">Toggle navigation menu</span>
            </Button>
          </SheetTrigger>
          <SheetContent side="right" className="p-6 w-[300px]">
            <div className="flex flex-col gap-4">
              <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
                Services
              </Link>
              <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
                Doctors
              </Link>
              <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
                About
              </Link>
              <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
                Contact
              </Link>
              <Button variant="outline" className="w-full">
                Book Appointment
              </Button>
            </div>
          </SheetContent>
        </Sheet>
      </header>
      <main className="flex-1">
        <section
          className="bg-primary bg-center py-24 px-6 md:px-12 lg:px-24 flex flex-col items-center justify-center text-center">
          <h1
            className="text-3xl md:text-5xl font-bold text-primary-foreground max-w-3xl">
            Exceptional Healthcare for Your Well-Being
          </h1>
          <p className="text-lg md:text-xl text-primary-foreground max-w-2xl mt-4">
            Experience the best in medical care at our state-of-the-art hospital. Book your appointment today.
          </p>
          <Button size="lg" className="mt-8 bg-secondary  border-secondary border-2">
            Book Appointment
          </Button>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-6 md:px-12 lg:px-24">
          <div className="max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">Our Services</h2>
              <p className="text-muted-foreground text-lg md:text-xl">Explore our wide range of medical services.</p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <HeartPulseIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Cardiology</h3>
                  <p className="text-muted-foreground text-center">
                    Our expert cardiologists provide comprehensive heart health services.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <MicroscopeIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Laboratory</h3>
                  <p className="text-muted-foreground text-center">
                    Our state-of-the-art laboratory offers accurate and reliable diagnostic services.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <AmbulanceIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Emergency</h3>
                  <p className="text-muted-foreground text-center">
                    Our emergency department is equipped to handle any medical crisis.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <PillBottleIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Pharmacy</h3>
                  <p className="text-muted-foreground text-center">
                    Our on-site pharmacy provides convenient access to essential medications.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <StethoscopeIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Outpatient Clinic</h3>
                  <p className="text-muted-foreground text-center">
                    Our outpatient clinic offers comprehensive medical care for all your needs.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <ShipWheelIcon className="h-10 w-10 text-primary" />
                  <h3 className="text-xl font-semibold">Physical Therapy</h3>
                  <p className="text-muted-foreground text-center">
                    Our physical therapy department helps you regain strength and mobility.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20 px-6 md:px-12 lg:px-24">
          <div className="max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">Schedule a Visit</h2>
              <p className="text-muted-foreground text-lg md:text-xl">Fill out the form to book your appointment.</p>
            </div>
            <form className="mt-8 grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="grid gap-4">
                <Input label="First Name" placeholder="Enter your first name" />
                <Input label="Last Name" placeholder="Enter your last name" />
                <Input label="Email" type="email" placeholder="Enter your email" />
                <Input label="Phone" type="tel" placeholder="Enter your phone number" />
              </div>
              <div className="grid gap-4">
                <Textarea label="Reason for Visit" placeholder="Describe your medical concern" />
                <Popover>
                  <PopoverTrigger asChild>
                    <Button variant="outline" className="flex-col items-start w-full h-auto">
                      <span className="font-semibold uppercase text-[0.65rem]">Preferred Date</span>
                      <span className="font-normal">4/2/2024</span>
                    </Button>
                  </PopoverTrigger>
                  <PopoverContent className="p-0 max-w-[276px]">
                    <Calendar />
                  </PopoverContent>
                </Popover>
                <Button type="submit" size="lg">
                  Schedule Appointment
                </Button>
              </div>
            </form>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-6 md:px-12 lg:px-24">
          <div className="max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">About Acme Hospital</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Learn more about our state-of-the-art facility and experienced medical team.
              </p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-8">
              <div>
                <img
                  src="/placeholder.svg"
                  width="550"
                  height="310"
                  alt="Hospital"
                  className="rounded-lg object-cover" />
              </div>
              <div className="space-y-4">
                <p>
                  Acme Hospital is a leading healthcare provider in the region, offering a wide range of medical
                  services to patients of all ages. Our state-of-the-art facility is equipped with the latest technology
                  and staffed by a team of experienced and compassionate medical professionals.
                </p>
                <p>
                  At Acme Hospital, we are committed to providing exceptional care and ensuring the well-being of our
                  patients. Our mission is to deliver personalized healthcare solutions that address the unique needs of
                  each individual.
                </p>
                <Link
                  href="#"
                  className="inline-flex items-center gap-2 text-primary hover:underline"
                  prefetch={false}>
                  Learn More <ArrowRightIcon className="h-4 w-4" />
                </Link>
              </div>
            </div>
          </div>
        </section>
        <section className="bg-muted py-12 md:py-16 lg:py-20 px-6 md:px-12 lg:px-24">
          <div className="max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">Our Doctors</h2>
              <p className="text-muted-foreground text-lg md:text-xl">
                Meet our experienced and dedicated medical team.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <Avatar className="w-20 h-20">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <h3 className="text-xl font-semibold">Dr. John Doe</h3>
                  <p className="text-muted-foreground">Cardiologist</p>
                  <p className="text-center">
                    Dr. Doe has over 15 years of experience in the field of cardiology and is dedicated to providing
                    exceptional care to his patients.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <Avatar className="w-20 h-20">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>JS</AvatarFallback>
                  </Avatar>
                  <h3 className="text-xl font-semibold">Dr. Jane Smith</h3>
                  <p className="text-muted-foreground">Pediatrician</p>
                  <p className="text-center">
                    Dr. Smith is a highly skilled pediatrician with a passion for providing compassionate care to
                    children and their families.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col items-center gap-4">
                  <Avatar className="w-20 h-20">
                    <AvatarImage src="/placeholder-user.jpg" />
                    <AvatarFallback>MJ</AvatarFallback>
                  </Avatar>
                  <h3 className="text-xl font-semibold">Dr. Michael Johnson</h3>
                  <p className="text-muted-foreground">Orthopedic Surgeon</p>
                  <p className="text-center">
                    Dr. Johnson is a renowned orthopedic surgeon with extensive experience in joint replacement and
                    sports medicine.
                  </p>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20 px-6 md:px-12 lg:px-24">
          <div className="max-w-5xl mx-auto">
            <div className="text-center space-y-4">
              <h2 className="text-3xl md:text-4xl font-bold">Patient Testimonials</h2>
              <p className="text-muted-foreground text-lg md:text-xl">Hear from our satisfied patients.</p>
            </div>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 mt-8">
              <Card>
                <CardContent className="p-6 flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <Avatar className="w-12 h-12">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>SJ</AvatarFallback>
                    </Avatar>
                    <div>
                      <h3 className="text-lg font-semibold">Sarah Johnson</h3>
                      <p className="text-muted-foreground">Satisfied Patient</p>
                    </div>
                  </div>
                  <p>
                    "The staff at Acme Hospital were incredibly kind and\n attentive. They made me feel comfortable and
                    cared for\n throughout my entire visit."
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="p-6 flex flex-col gap-4">
                  <div className="flex items-center gap-4">
                    <Avatar className="w-12 h-12">
                      <AvatarImage src="/placeholder-user.jpg" />
                      <AvatarFallback>ML</AvatarFallback>
                    </Avatar>
                    <div>
                      <h3 className="text-lg font-semibold">Michael Lee</h3>
                      <p className="text-muted-foreground">Satisfied Patient</p>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>)
  );
}

function AmbulanceIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M10 10H6" />
      <path d="M14 18V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v11a1 1 0 0 0 1 1h2" />
      <path
        d="M19 18h2a1 1 0 0 0 1-1v-3.28a1 1 0 0 0-.684-.948l-1.923-.641a1 1 0 0 1-.578-.502l-1.539-3.076A1 1 0 0 0 16.382 8H14" />
      <path d="M8 8v4" />
      <path d="M9 18h6" />
      <circle cx="17" cy="18" r="2" />
      <circle cx="7" cy="18" r="2" />
    </svg>)
  );
}


function ArrowRightIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>)
  );
}


function HeartPulseIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M19 14c1.49-1.46 3-3.21 3-5.5A5.5 5.5 0 0 0 16.5 3c-1.76 0-3 .5-4.5 2-1.5-1.5-2.74-2-4.5-2A5.5 5.5 0 0 0 2 8.5c0 2.3 1.5 4.05 3 5.5l7 7Z" />
      <path d="M3.22 12H9.5l.5-1 2 4.5 2-7 1.5 3.5h5.27" />
    </svg>)
  );
}


function HospitalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 6v4" />
      <path d="M14 14h-4" />
      <path d="M14 18h-4" />
      <path d="M14 8h-4" />
      <path
        d="M18 12h2a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2h2" />
      <path d="M18 22V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v18" />
    </svg>)
  );
}


function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MicroscopeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 18h8" />
      <path d="M3 22h18" />
      <path d="M14 22a7 7 0 1 0 0-14h-1" />
      <path d="M9 14h2" />
      <path d="M9 12a2 2 0 0 1-2-2V6h6v4a2 2 0 0 1-2 2Z" />
      <path d="M12 6V3a1 1 0 0 0-1-1H9a1 1 0 0 0-1 1v3" />
    </svg>)
  );
}


function PillBottleIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 11h-4a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h4" />
      <path d="M6 7v13a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V7" />
      <rect width="16" height="5" x="4" y="2" rx="1" />
    </svg>)
  );
}


function ShipWheelIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="8" />
      <path d="M12 2v7.5" />
      <path d="m19 5-5.23 5.23" />
      <path d="M22 12h-7.5" />
      <path d="m19 19-5.23-5.23" />
      <path d="M12 14.5V22" />
      <path d="M10.23 13.77 5 19" />
      <path d="M9.5 12H2" />
      <path d="M10.23 10.23 5 5" />
      <circle cx="12" cy="12" r="2.5" />
    </svg>)
  );
}


function StethoscopeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M4.8 2.3A.3.3 0 1 0 5 2H4a2 2 0 0 0-2 2v5a6 6 0 0 0 6 6v0a6 6 0 0 0 6-6V4a2 2 0 0 0-2-2h-1a.2.2 0 1 0 .3.3" />
      <path d="M8 15v1a6 6 0 0 0 6 6v0a6 6 0 0 0 6-6v-4" />
      <circle cx="20" cy="10" r="2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
