/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/cwmlC9PGfLx
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Card, CardContent } from "@/components/ui/card"
import { Avatar } from "@/components/ui/avatar"
import { Separator } from "@/components/ui/separator"
import Services from "./Services"
import About from "./About"
import Schedule from "./Schedule"
import Rooms from "./Rooms"

const doctors = [
  {
    name: "Dr. Sarah Johnson",
    specialty: "Pediatrics",
    location: "New York, NY",
    rating: 4.8,
  },
  {
    name: "Dr. Michael Lee",
    specialty: "Cardiology",
    location: "Los Angeles, CA",
    rating: 4.9,
  },
  {
    name: "Dr. Emily Chen",
    specialty: "Dermatology",
    location: "Chicago, IL",
    rating: 4.7,
  },
  {
    name: "Dr. David Patel",
    specialty: "Orthopedics",
    location: "Houston, TX",
    rating: 4.6,
  },
  {
    name: "Dr. Sophia Gonzalez",
    specialty: "Obstetrics",
    location: "Miami, FL",
    rating: 4.9,
  },
  {
    name: "Dr. William Kim",
    specialty: "Neurology",
    location: "Seattle, WA",
    rating: 4.8,
  },
]

export function ComponentTwo() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="bg-primary text-primary-foreground py-6 absolute top-0 left-0 w-full z-50">
        <div className="container flex items-center justify-between px-10">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <HospitalIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">MedCare</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Find Doctors
            </Link>
            <Link href="/rooms" className="hover:underline underline-offset-4" prefetch={false}>
              Rooms
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              About Us
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Contact
            </Link>
          </nav>
          <Button className="bg-secondary">Book Appointment</Button>
        </div>
      </header>
      <main>
        <section className="px-10 bg-primary h-screen flex items-center justify-center pt-16">
          <div className="container grid md:grid-cols-2 gap-6 items-center">
            <div className="space-y-4">
              <h1
                className="text-3xl font-bold text-primary-foreground sm:text-4xl md:text-5xl">
                Find the Best Healthcare for You
              </h1>
              <p className="text-primary-foreground/80 md:text-xl">
                Our hospital offers a wide range of medical services and experienced doctors to provide you with the
                best care.
              </p>
              <Button
                variant="solid"
                className="bg-secondary text-secondary-foreground hover:bg-secondary/90">
                Book Appointment
              </Button>
            </div>
            <img
              src="/placeholder.svg"
              width={600}
              height={400}
              alt="Hero Image"
              className="mx-auto rounded-xl p-5" />
          </div>
        </section>
        <Services />
        <section className="px-10 py-12 md:py-24">
          <div className="container">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl font-bold">Our Doctors</h2>
              <div className="flex items-center gap-2">
                <Input
                  type="text"
                  placeholder="Search by name, specialty, or location"
                  className="max-w-xs" />
                <Button variant="outline">
                  <SearchIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {doctors.map((doctor, index) => (
                <Card key={index}>
                  <CardContent className="p-6 space-y-4">
                    <div className="flex items-center gap-4">
                      <Avatar
                        className="bg-primary text-primary-foreground w-12 h-12 flex items-center justify-center rounded-full">
                        {doctor.name.charAt(0)}
                      </Avatar>
                      <div>
                        <h3 className="font-semibold">{doctor.name}</h3>
                        <p className="text-muted-foreground">{doctor.specialty}</p>
                        <p className="text-muted-foreground">{doctor.location}</p>
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex items-center gap-1 text-xs font-semibold">
                        <StarIcon className="h-4 w-4 fill-primary" />
                        <span>{doctor.rating}</span>
                      </div>
                      <Separator orientation="vertical" className="h-4" />
                      <Button variant="outline" className="ml-auto">
                        Book Appointment
                      </Button>
                    </div>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
        <Rooms />
        <section className="px-10 bg-muted py-12 md:py-24">
          <div className="container">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl font-bold">Our Departments</h2>
              <div className="flex items-center gap-2">
                <Input
                  type="text"
                  placeholder="Search by name or specialty"
                  className="max-w-xs" />
                <Button variant="outline">
                  <SearchIcon className="h-4 w-4" />
                </Button>
              </div>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              {[
                {
                  name: "Pediatrics",
                  description: "Our pediatric department provides comprehensive care for children of all ages.",
                  services: ["Well-child visits", "Immunizations", "Sick visits"],
                },
                {
                  name: "Cardiology",
                  description:
                    "Our cardiology department specializes in the diagnosis and treatment of heart conditions.",
                  services: ["Echocardiograms", "Stress tests", "Cardiac catheterization"],
                },
                {
                  name: "Dermatology",
                  description:
                    "Our dermatology department offers a wide range of treatments for skin, hair, and nail conditions.",
                  services: ["Acne treatment", "Skin cancer screening", "Laser treatments"],
                },
                {
                  name: "Orthopedics",
                  description:
                    "Our orthopedic department specializes in the diagnosis and treatment of musculoskeletal conditions.",
                  services: ["Joint replacement", "Fracture care", "Physical therapy"],
                },
                {
                  name: "Obstetrics",
                  description:
                    "Our obstetrics department provides comprehensive care for women throughout their pregnancy and postpartum.",
                  services: ["Prenatal care", "Delivery services", "Postpartum care"],
                },
                {
                  name: "Neurology",
                  description:
                    "Our neurology department specializes in the diagnosis and treatment of conditions affecting the brain, spinal cord, and nervous system.",
                  services: ["Stroke treatment", "Epilepsy management", "Headache treatment"],
                },
              ].map((department, index) => (
                <Card key={index}>
                  <CardContent className="p-6 space-y-4">
                    <h3 className="font-semibold">{department.name}</h3>
                    <p className="text-muted-foreground">{department.description}</p>
                    <ul className="space-y-2 text-muted-foreground">
                      {department.services.map((service, serviceIndex) => (
                        <li key={serviceIndex}>
                          <CheckIcon className="mr-2 inline-block h-4 w-4 fill-primary" />
                          {service}
                        </li>
                      ))}
                    </ul>
                    <Button variant="outline" className="ml-auto">
                      Learn More
                    </Button>
                  </CardContent>
                </Card>
              ))}
            </div>
          </div>
        </section>
        <About />
        <Schedule />
      </main>
      <footer className="bg-primary text-primary-foreground py-6 px-4 md:px-6">
        <div
          className="container flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <HospitalIcon className="h-6 w-6" />
            <span className="text-lg font-semibold">MedCare</span>
          </div>
          <nav className="flex items-center gap-4">
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Privacy Policy
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Terms of Service
            </Link>
            <Link href="#" className="hover:underline underline-offset-4" prefetch={false}>
              Contact Us
            </Link>
          </nav>
          <div className="text-sm text-primary-foreground/80">&copy; 2024 MedCare. All rights reserved.</div>
        </div>
      </footer>
    </div>)
  );
}

function CheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M20 6 9 17l-5-5" />
    </svg>)
  );
}


function HospitalIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M12 6v4" />
      <path d="M14 14h-4" />
      <path d="M14 18h-4" />
      <path d="M14 8h-4" />
      <path
        d="M18 12h2a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H4a2 2 0 0 1-2-2v-9a2 2 0 0 1 2-2h2" />
      <path d="M18 22V4a2 2 0 0 0-2-2H8a2 2 0 0 0-2 2v18" />
    </svg>)
  );
}


function SearchIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>)
  );
}


function StarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polygon
        points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>)
  );
}


function XIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>)
  );
}
